<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Liu, Felix">

<title>Growing in the Margins of Men’s Narration</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="Liu_FullVersion_Html_files/libs/clipboard/clipboard.min.js"></script>
<script src="Liu_FullVersion_Html_files/libs/quarto-html/quarto.js"></script>
<script src="Liu_FullVersion_Html_files/libs/quarto-html/popper.min.js"></script>
<script src="Liu_FullVersion_Html_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Liu_FullVersion_Html_files/libs/quarto-html/anchor.min.js"></script>
<link href="Liu_FullVersion_Html_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Liu_FullVersion_Html_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Liu_FullVersion_Html_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Liu_FullVersion_Html_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Liu_FullVersion_Html_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

<script src="Liu_FullVersion_Html_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="Liu_FullVersion_Html_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Growing in the Margins of Men’s Narration</h1>
<p class="subtitle lead">How Women Poets Claimed Literary Recognition in Imperial China</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Liu, Felix </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<style>
  body {
  text-align: justify}
</style>
<div style="page-break-after: always;"></div>
<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Female writers in both ancient China and the West faced significant social and economic challenges that hindered their establishment in the literary world. Support from male relatives and friends became crucial for creating and sharing their work, with numerous studies highlighting the impact of these relationships in a male-dominated landscape. Additionally, social networks were vital for women to gain literary recognition, as they often relied on support from husbands, family members, and friends to enhance their visibility in the literary community. This project aims to clarify how social capital influenced women’s literary achievements and recognition in ancient China.</p>
<p>This project will examine how social networks, especially connections with male elites, influenced women’s literary status and their opportunities for having individual collections (<em>Bieji 别集</em>) published in ancient China. This topic carries profound implications for understanding:</p>
<ul>
<li>The impact of social capital on women’s access to literary resources and recognition.</li>
<li>The relative influence of different types of social capital, particularly the role of male gatekeepers, in determining women’s literary visibility.</li>
</ul>
<p>Two primary databases were utilized in this study, both of which are focused on historical figures from ancient China. <a href="https://projects.iq.harvard.edu/cbdb">The China Biographical Database (CBDB)</a> is a freely accessible relational database with biographical information about 641,568 individuals as of August 2024, primarily from the 7th through 19th centuries <span class="citation" data-cites="cbdb">[@cbdb]</span>. <strong>The total size of the database is 1.9 GB, which includes 87 different data tables</strong> stored in the <code>db</code> file. <a href="https://digital.library.mcgill.ca/mingqing/english/index.php">Ming Qing Women’s Writing (MQWW)</a> is a comprehensive database, totaling 23.5 MB, featuring poetry and writings by women from late imperial to modern China. <strong>This archive enables users to match women authors with CBDB for detailed demographic and social network information.</strong> These two datasets include numerous tables, necessitating complex SQL queries to clean and extract the information relevant to this study.</p>
<p>Using a three-step approach with the LASSO model, I aimed to identify the causal effect of social capital on women poets’ literary recognition. The findings indicate that <strong>the connections with male elites indeed influenced women’s literary status. However, only social relation networks influence the literary recognition of women poets, while the effect of kinship network centrality was found to be non-significant.</strong></p>
</section>
<section id="variables-mesurement" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Variables Mesurement</h1>
<section id="response-womens-literary-recognition" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="response-womens-literary-recognition"><span class="header-section-number">2.1</span> Response: Women’s Literary Recognition</h2>
<p>My response variable to measure women’s literary recognition is whether women poets have published their own individual collections (Bieji/別集). Anthologies (Zongji/總集, including all of other worktypes) typically include works that are representative or influential, but they do not fully reflect the complete body of work and value of an individual author. In contrast, individual collections better showcase the personal creative characteristics and literary styles of a specific writer, and can better demonstrate their unique literary achievements.</p>
<p>Compared to anthologies, which tend to reflect the mainstream evaluation standards of the literary community at the time and are often biased towards male perspectives, the curation of individual collections is more likely to focus on the personal writings of women authors, highlighting their unique perspectives and modes of expression. This makes individual collections more conducive to the objective assessment of the status of women’s literary works.</p>
<p>Therefore, <strong>if a woman poet has published at least one individual collection (Bieji &gt; 0), I will conclude that her literary status has been recognized</strong>.</p>
<p><span class="math display">\[
Y = I (Bieji &gt; 0)
\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(Y\)</span> represents the response variable of women’s literary recognition</li>
<li><span class="math inline">\(I\)</span> is the indicator function, which takes the value of 1 if the condition <span class="math inline">\(Bieji &gt; 0\)</span> is true, and 0 otherwise.</li>
</ul>
<p>The plot (<a href="#fig-worktype">Figure&nbsp;1</a>) on the right illustrates that while most women poets have published anthologies, only 27% have produced individual collections, highlighting a significant disparity in literary recognition.</p>
<div class="cell" data-layout-align="center" data-hash="Liu_FullVersion_Html_cache/html/fig-worktype_34067b4506f02e6cf4205e33c88ddc83">
<div class="cell-output cell-output-stdout">
<pre><code>TableGrob (1 x 2) "arrange": 2 grobs
  z     cells    name           grob
1 1 (1-1,1-1) arrange gtable[layout]
2 2 (1-1,2-2) arrange gtable[layout]</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-worktype" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Liu_FullVersion_Html_files/figure-html/fig-worktype-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Poem and Poet Number against Worktypes</figcaption>
</figure>
</div>
</div>
</div>
<p>The analytical framework of this study is as follows (<a href="#fig-structure">Figure&nbsp;2</a>). The primary predictor is social capital, which is divided into two components: kinship and social relations. Kinship focuses on social capital based on blood relations, while social relations focus on non-kinship and non-inherited social capital. In addition to these primary predictors, the study will also control for other major variables that may potentially influence the outcome variable (women’s literary recognition). The measurement approaches for these other variables will be detailed in the subsequent sections.</p>
<div id="fig-structure" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="output/images/structure.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;2: Analysis Framework</figcaption>
</figure>
</div>
</section>
<section id="primary-predictor-social-capital" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="primary-predictor-social-capital"><span class="header-section-number">2.2</span> Primary Predictor: Social Capital</h2>
<p>As mentioned, this study measures social capital through kinship and social relationships. Specifically, the kinship networks consist solely of immediate relatives, which include Ascending Kin, Descending Kin, Affinal Kin, and Collateral Kin. In contrast, social relations encompass ten different types of relationships defined in previous studies, such as Academic Relations, Political Ties, Patronage, Social Network, Literary Work, Artistic Exchange, Ceremonial Ties, Correspondence, Service Links, and Economic Ties.</p>
<p>Here is an overview of women poets’ social networks. The network adjacency matrices (<a href="#fig-net-1">Figure&nbsp;3</a>) illustrate the connections among women poets, with the x-axis representing the poets themselves and the y-axis indicating their relationships with specific individuals. The matrix on the left focuses on kinship relations, while the one on the right emphasizes social relations. <a href="#tbl-net">Table&nbsp;1</a> presents the descriptive statistics for connections among women poets based on two relationship types. Overall, the data indicates that social relations exhibit a greater mean number of connections than kinship ties, suggesting a richer network among women poets in terms of social relationships (It is mainly due to social ties containing more kinds of relationships selected).</p>
<div class="cell" data-layout-align="center" data-hash="Liu_FullVersion_Html_cache/html/fig-net-1_150c5cf5e925e8a9f8a1250be5c509a8">
<div class="cell-output cell-output-stdout">
<pre><code>TableGrob (1 x 2) "arrange": 2 grobs
  z     cells    name           grob
1 1 (1-1,1-1) arrange gtable[layout]
2 2 (1-1,2-2) arrange gtable[layout]</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-net-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Liu_FullVersion_Html_files/figure-html/fig-net-1-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;3: Adjacency Matrices of Women Poets (Source: CBDB)</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-hash="Liu_FullVersion_Html_cache/html/tbl-net_ebbffc91efe8536ccccf81bcd7d84e60">
<div class="cell-output-display">
<div id="tbl-net" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;1: Descriptive Statistics of Connections by Relationship Type</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Relationship Type</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">Max</th>
<th style="text-align: right;">Q25</th>
<th style="text-align: right;">Q75</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Social Relations</td>
<td style="text-align: right;">202</td>
<td style="text-align: right;">3.11</td>
<td style="text-align: right;">2.95</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kinship</td>
<td style="text-align: right;">442</td>
<td style="text-align: right;">2.41</td>
<td style="text-align: right;">1.46</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The violin plot (<a href="#fig-net-2">Figure&nbsp;4</a>) illustrates the distribution of connections by relationship types, comparing poets with individual collections to those without. The data reveals that connections within social relations are significantly denser and more varied compared to those within kinship ties. Furthermore, regardless of the relationship type, women who have published individual collections exhibit higher mean connection values. Specifically, the mean connections for women poets without individual collections are lower (Mean: 2.221 for kinship and 2.532 for social relations) compared to those who have published their individual works (Mean: 2.752 for kinship and 3.611 for social relations), reinforcing the conclusion that having an individual collection correlates with a more extensive social network.</p>
<div class="cell" data-layout-align="center" data-hash="Liu_FullVersion_Html_cache/html/fig-net-2_7db5812715a58f5df896828840cd1a66">
<div class="cell-output-display">
<div id="fig-net-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Liu_FullVersion_Html_files/figure-html/fig-net-2-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;4: Descriptive Statistics of Women Poets’ Connections by Relationship Type</figcaption>
</figure>
</div>
</div>
</div>
<p>Here is a typical example of women having limited opportunities to expand their social capital in ancient China. Zhao Mingcheng had a much richer network than Li Qingzhao (<a href="#fig-limited">Figure&nbsp;6</a>). Despite being more famous in modern times, Li had constrained social networks (<a href="#fig-ngrams">Figure&nbsp;5</a>).</p>
<div class="cell" data-layout-align="center" data-hash="Liu_FullVersion_Html_cache/html/fig-ngrams_f751f020d17b86551c7e395299c2cb72">
<div class="cell-output-display">
<div id="fig-ngrams" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Liu_FullVersion_Html_files/figure-html/fig-ngrams-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;5: Frequency of Names Over Time (1980-2022) by Corpus (Source: Google Ngrams)</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center" data-hash="Liu_FullVersion_Html_cache/html/fig-limited_61bccfae959c2c625f75e8c6ffe13955">
<div class="cell-output cell-output-stdout">
<pre><code>TableGrob (2 x 1) "arrange": 2 grobs
  z     cells    name           grob
1 1 (1-1,1-1) arrange gtable[layout]
2 2 (2-2,1-1) arrange gtable[layout]</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-limited" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Liu_FullVersion_Html_files/figure-html/fig-limited-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;6: Personal Relationship Network of Li Qingzhao, Zhao Mingcheng (Source: CBDB)</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="summary-of-other-predictors" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="summary-of-other-predictors"><span class="header-section-number">2.3</span> Summary of Other Predictors</h2>
<p>In addition to social capital, other predictors are also controlled for in our model. Regarding the temporal dimension, the distribution of women poets spans different historical periods, from the Eastern Han to the Qing Dynasty. Since different dynasties may exert varying influences, the dynasty is considered an important variable. As shown in <a href="#fig-dynasty">Figure&nbsp;7</a>, most of the observations (~87%) were born during the Qing Dynasty, followed by the Tang Dynasty (~5%).</p>
<div class="cell" data-layout-align="center" data-hash="Liu_FullVersion_Html_cache/html/fig-dynasty_1f274d116d3712ff863f84e5053d0586">
<div class="cell-output-display">
<div id="fig-dynasty" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Liu_FullVersion_Html_files/figure-html/fig-dynasty-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;7: Distribution of Women Poets across Dynasties</figcaption>
</figure>
</div>
</div>
</div>
<p>In terms of the spatial dimension, I accounted for the administrative provinces of the women poets’ birthplaces. As illustrated in the plot (<a href="#fig-region">Figure&nbsp;8</a>), some provinces had significantly more women poets than others, which can be attributed to the structural mechanisms within those regions.</p>
<p>Additionally, I controlled for local education levels by examining the number of successful candidates (also known as palace graduates) in the imperial examination (jinshi 進士 / juren 舉人 / jieyuan 解元) within a 50 km radius of the women poets’ birthplaces, which is roughly equivalent to the same administrative region. A higher number of local palace graduates can be interpreted as an indication of more advanced education in that area. The spatial distribution of palace graduates’ birthplaces is shown in <a href="#fig-jinshi">Figure&nbsp;9</a>.</p>
<div class="cell" data-layout-align="center" data-hash="Liu_FullVersion_Html_cache/html/fig-region_25fa3e53e17a15c17d267091af6a9854">
<div class="cell-output cell-output-stdout">
<pre><code>TableGrob (1 x 2) "arrange": 2 grobs
  z     cells    name           grob
1 1 (1-1,1-1) arrange gtable[layout]
2 2 (1-1,2-2) arrange gtable[layout]</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-region" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Liu_FullVersion_Html_files/figure-html/fig-region-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;8: Spatial Distribution of Women Poet by Province (Source: CBDB)</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center" data-hash="Liu_FullVersion_Html_cache/html/fig-jinshi_3a36b0af94d827e80e1563b1ee97c514">
<div class="cell-output cell-output-stdout">
<pre><code>TableGrob (1 x 2) "arrange": 2 grobs
  z     cells    name           grob
1 1 (1-1,1-1) arrange gtable[layout]
2 2 (1-1,2-2) arrange gtable[layout]</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-jinshi" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Liu_FullVersion_Html_files/figure-html/fig-jinshi-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;9: Spatial Distribution of Palace Graduates Birthplaces (Source: CBDB)</figcaption>
</figure>
</div>
</div>
</div>
<p>In assessing social status, I consider the highest social status attained by the family members of women poets. This approach is justified for two primary reasons: First, women in ancient China had limited opportunities to acquire social resources, as their status was often linked to their family members, particularly male relatives (未嫁从父/出嫁从夫/夫死从子). Second, the highest social status of family members serves as an indicative measure of the resources that women poets could potentially access.</p>
<p>The detailed measurement involves identifying family members based on the following criteria: 1. whether they have been recorded biographically as core figures; 2. whether they held the status of palace graduates; 3. whether they held official positions; 4. whether they received official honors or recognitions; and 5. whether they were distinguished writers or historians (<a href="#fig-se">Figure&nbsp;10</a>).</p>
<div class="cell" data-layout-align="center" data-hash="Liu_FullVersion_Html_cache/html/fig-se_d560af515aabdc8f74304ed550b63a29">
<div class="cell-output-display">
<div id="fig-se" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Liu_FullVersion_Html_files/figure-html/fig-se-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;10: Distribution of Social Status Indicators (Direct Kinship Network)</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="methodology-and-analysis" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Methodology and Analysis</h1>
<p>Given the high-dimensional nature of the data (n = 443, p = 1391), a LASSO model was applied in this study. As the formula illustrates, the lasso imposes a penalty on the absolute size of the coefficients, encouraging sparsity in the model. This penalty helps to mitigate overfitting by selecting a subset of relevant features while effectively shrinking the coefficients of less important predictors to zero. The optimal lambda value was selected through cross-validation based on the AICc criterion.</p>
<p><span class="math display">\[ \hat{\beta}_{\text{LASSO}} = \underset{\beta}{\operatorname{argmin}} \left\{ \sum_{i=1}^{n} (y_i - X_i\beta)^2 + \lambda \sum_{j=1}^{p} |\beta_j| \right\} \]</span></p>
<section id="individual-effects-within-networks" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="individual-effects-within-networks"><span class="header-section-number">3.1</span> Individual Effects Within Networks</h2>
<p>In the initial LASSO model, all social capital variables were treated as one-hot variables to systematically evaluate the impact of male individuals on women’s literary recognition. The results of this initial LASSO model are illustrated in <a href="#fig-lasso">Figure&nbsp;11</a>. The findings present several important observations:</p>
<ol type="1">
<li><p>A considerable number of individuals within both kinship and social relations exert a positive influence on women’s literary recognition. This suggests that the presence and support of male family members and social contacts play a crucial role in enhancing women poets’ visibility and acclaim.</p></li>
<li><p>The mean coefficient for kinship (0.438) is significantly larger than that for social relations (0.201), indicating that familial ties may have a more pronounced impact on literary recognition than connections outside the family unit. Specifically, on average, the presence of a kinship connection increases the odds of literary recognition by 55%, while a social connection increases the odds by 22%, holding other variables constant (OR_kinship = 1.55; OR_social = 1.22).</p></li>
<li><p>Furthermore, the coefficients for the spatial and temporal variables are also markedly greater than those associated with social relations. This observation underscores the importance of geographical and historical contexts in shaping the literary landscape, suggesting that both the location and timing of a poet’s work are critical factors influencing their recognition.</p></li>
</ol>
<p>However, the violin plot reveals a significant dispersion in the effects of social capital, indicating that the impact of different individuals varies greatly within the dataset. This finding suggests that while social capital plays a positive role in women’s literary recognition, it complicates the assessment of its overall influence on women as a group. The next step is to delve deeper into the aggregate impact of social capital on women’s literary achievements.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-lasso" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Liu_FullVersion_Html_files/figure-html/fig-lasso-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;11: Distribution of LASSO Coefficients by Predictor Types</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="centrality-effects-in-networks" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="centrality-effects-in-networks"><span class="header-section-number">3.2</span> Centrality Effects in Networks</h2>
<p>To measure the centrality effects in networks on women poets, centrality degree metrics were calculated and applied to the model. The measurement of individual relationships may contain more noise; thus, degree serves as an aggregated indicator that can help smooth out these measurement errors to some extent. The existence of effects from aggregated indicators suggests that the network exhibits “wholeness” or “scale effects,” indicating the implications of these aggregated relationships.</p>
<p><strong>Kinship Degree (0.102)</strong>: This predictor demonstrates a positive but relatively modest influence on women’s literary recognition compared to social relations, which is notably different from the results of the initial model. The coefficient means when kinship degree of women poets increase 1 unit, holding all other variables constant, the odds ratio of their literary status can be recognised will increase by 10.7% (OR = 1.107).</p>
<p><strong>Social Degree (0.223)</strong>: The coefficient for social degree is higher than that of kinship. This implies that broader social interactions have a more pronounced effect on women’s literary achievements, thereby enhancing their recognition within the literary community. The coefficient indicates that when social degree increases by 1 unit, the Odds Ratio of women poets being literary recognized will increase by 25% (OR = 1.25).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-degree" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Liu_FullVersion_Html_files/figure-html/fig-degree-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;12: Mean LASSO Coefficients by Predictor Types</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="identification-of-causal-effects" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="identification-of-causal-effects"><span class="header-section-number">3.3</span> Identification of Causal Effects</h2>
<p>Due to potential correlations among different predictors, it is difficult to assert that the estimated coefficients from the above LASSO model—Kinship Degree (0.102) and Social Degree (0.223)—reflect their true impact on women’s literary status recognition. To obtain a more accurate treatment effect of the social capital degree indicator, I will conduct a double LASSO analysis.</p>
<p>Our empirical strategy employs a Double LASSO procedure that unfolds in two stages. In the first stage, I estimate the treatment equation:</p>
<p><span class="math display">\[ d_i = \gamma'Z_i + v_i \]</span> <span class="math display">\[ \hat{d}_i = \hat{\gamma}'Z_i \]</span></p>
<p>where <span class="math inline">\(d_i\)</span> denotes the treatment variable (the network degree centrality), <span class="math inline">\(Z_i\)</span> is a vector of control variables, and <span class="math inline">\(\gamma\)</span> is estimated using LASSO regression. The predicted values <span class="math inline">\(\hat{d}_i\)</span> are then obtained using the estimated coefficients.</p>
<p>In the second stage, I estimate the outcome equation:</p>
<p><span class="math display">\[ y_i = \beta d_i + \delta\hat{d}_i + \theta'Z_i + \epsilon_i \]</span></p>
<p>where <span class="math inline">\(\beta\)</span> captures the treatment effect of network centrality on the outcome variable, while controlling for both the original treatment <span class="math inline">\(d_i\)</span> and its prediction <span class="math inline">\(\hat{d}_i\)</span> from the first stage. The control variables <span class="math inline">\(Z_i\)</span> are included in both stages, and the treatment variables are left unpenalized in the second stage estimation.</p>
<p>I conducted double LASSO analysis separately for the kinship degree and social degree indicators. Table 3.1 presents the estimation results of the double LASSO regression. The effect of social degree is 0.211, which is quite close to the naive LASSO result of 0.223, while the effect of kinship degree is nearly 0 (significantly lower than the naive LASSO estimate of 0.102). This indicates that the influence of kinship degree can be fully explained by social degree and other predictors.</p>
<div class="cell" data-hash="Liu_FullVersion_Html_cache/html/double-1_3924171d9ba4651064b7db55002bf080">
<div class="cell-output-display">
<table class="table table-striped table-hover table-sm small" data-quarto-postprocess="true">
<caption>Comparison of LASSO Treatment Effects</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold;">Network Type</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold;">Naive LASSO</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold;">Double LASSO</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em; font-weight: bold;">Social Degree</td>
<td style="text-align: left; width: 10em;">0.223</td>
<td style="text-align: left; width: 10em;">0.211</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em; font-weight: bold;">Kinship Degree</td>
<td style="text-align: left; width: 10em;">0.102</td>
<td style="text-align: left; width: 10em;">0.000</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Note: </span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> Estimates from LASSO regressions using gamlr package.</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup>1</sup> Treatment variables (d and dhat) were not penalized in the estimation.</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup>2</sup> Controls include dynasty, region, and status variables.</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
<p>To validate these findings, I conducted a bootstrap analysis with 500 replications (<strong>?@fig-double-2</strong>). The results indicate that the effect of social connections is statistically significant, with an estimated coefficient of 0.287 (95% CI: [0.086, 0.489]). In contrast, the effect of kinship connections remains statistically insignificant, with an estimate of 0.092 (95% CI: [-0.096, 0.280]). The coefficient from the double LASSO analysis suggests that when the social degree of women poets increases by 1 unit, holding all other variables constant, the odds ratio for their literary recognition increases by 24.9% (OR = 1.249). Conversely, the coefficient for kinship degree does not show significant influence on women’s literary recognition. These bootstrap results further support our main findings that <strong>social connections, rather than kinship ties, play a more crucial role in determining career success</strong>.</p>
<div class="cell" data-hash="Liu_FullVersion_Html_cache/html/double-2_e6b160ba5584472613bd33e7575c3976">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed table-sm small" data-quarto-postprocess="true">
<caption>Double LASSO Treatment Effects (Bootstrap)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Network Type</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Estimate</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Std. Error</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em; font-weight: bold;">Social Degree</td>
<td style="text-align: left; width: 6em;">0.287</td>
<td style="text-align: left; width: 6em;">0.103</td>
<td style="text-align: left; width: 10em;">[0.086, 0.489]</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em; font-weight: bold;">Kinship Degree</td>
<td style="text-align: left; width: 6em;">0.092</td>
<td style="text-align: left; width: 6em;">0.096</td>
<td style="text-align: left; width: 10em;">[-0.096, 0.280]</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Note: </span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> Based on 500 bootstrap replications</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup>1</sup> Parallel processing using all available cores</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup>2</sup> Bootstrap samples with replacement</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tfoot>

</table>
</div>


</div>
</div>
</section>
</section>
<section id="discussion" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Discussion</h1>
<p>To estimate the effect of female-male social capital on the literary recognition of women poets, this research implemented a three-step approach.</p>
<p>First, a comprehensive network comprising numerous male individuals was analyzed using a LASSO model while controlling for other predictors. The results indicate that many male individuals positively impact the literary recognition of women poets, with the mean coefficient for kinship being significantly larger than that of social relations (<strong>kinship 0.436 &gt; social 0.201</strong>). Second, in measuring the network centrality effect, aggregated metrics, specifically the network degree, were utilized in the LASSO model instead of individual metrics. This analysis yielded a contrasting result; the centrality of social relation networks exhibited a greater influence on kinship network centrality (<strong>social 0.223 &gt; kinship 0.102</strong>). Finally, to eliminate the mutual impact of each variable and isolate the pure effect of social capital, a double LASSO model was deployed. The bootstrapping results demonstrated that social relation network centrality has a significantly positive impact on the literary recognition of women poets (<strong>social 0.287, OR = 1.249</strong>), whereas the effect of kinship network centrality proved to be non-significant. This suggests that only social relation networks influence the literary recognition of women poets.</p>
<p>The findings indicate that <strong>social connections (non-kinship) are more important for female literary figures than familial ties.</strong> This suggests that the recognition of literary achievements relies more heavily on actively established social circles than on inherent family relationships. Social networks may provide women with essential channels for disseminating their work, opportunities for literary exchange, and sources of creative inspiration. Although Chinese traditional perspectives suggest that women should prioritize family, the results of this study highlight that social connections that transcend familial boundaries are paramount for their success.</p>
<p>However, there are several points for improvement in the analysis.</p>
<p>The quality of the data is limited. Although the MQWW Database comprises over 6,000 observations, there is no key column available to facilitate merging with the CBDB Database. The data can only be merged based on the name column; however, many women in ancient China did not possess their own names, even if they were writers. This reliance on names leads to messy and often inaccurate artificial data cleaning, resulting in fewer than 500 usable observations after filtering. Additionally, I believe that the quality of the poets’ works should be considered the most significant variable influencing their literary recognition. However, measuring this quality is particularly challenging. The absence of this variable may introduce an omitted variable bias, potentially affecting the final results. In future research, applying a Chinese segmentation approach could help better assess the quality or themes of the poets’ works, providing a clearer insight into their literary recognition.</p>
<p>I would like to conclude my project with a poem attributed to ‘周氏/Zhou Shi’ (a woman married to a man with the surname Zhou). I noticed these poets while reviewing my data. As I mentioned, many women poets were recorded without their own names, even though they created brilliant poetry. In this poem, she praises the plum blossoms that bloom in the cold winter and believes that, like the blossoms, she possesses a resilient character.</p>
<ul>
<li>“我有生來冰雪骨，與花同證歲寒心。”</li>
<li>“I am innately fearless of the chill, aspiring to bloom like the plum blossoms amid the cold.”</li>
</ul>
<div style="page-break-after: always;"></div>
</section>
<section id="references" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" role="list">

</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>